### ISSUE TITLE
Multiplex `eth_sendRawTransaction` to the builder.

### ISSUE THREAD

**Issue by ferranbt** [flashbots/rollup-boost#14]
Rollup-boost should multiplex the transactions sent with `eth_sendRawTransaction` to the builder too. Enable this behaviour with a flag.

**Comment by avalonche** [comment]
this is easier to do at the rpc endpoint level via nginx than natively inside rollup-boost due to restrictions in the jsonrpcsee library.

**Comment by ferranbt** [comment]
But with nginx you are adding an extra service to the mix, in this case the platform would do it natively.

Also, if `rollup-boost` had access to the transactions it could keep track on whether the builder is censoring them or not and act accordingly, for example, adding a few blocks from the proposer op-geth.
